### ISSUE TITLE
change email

### ISSUE THREAD

**Issue by Helias** [azerothcore/acore-cms#7]
I tried to change email and I got this:

![image](https://user-images.githubusercontent.com/519778/86652043-581d8600-bfe4-11ea-8a22-30512c60bf1b.png)

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getUsername() on null in /var/www/html/wp-content/plugins/acore-wp-plugin/src/hooks/user/user.php:39 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(287): ACore\user_profile_update_errors(Object(WP_Error), true, Object(stdClass)) #1 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /var/www/html/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #3 /var/www/html/wp-admin/includes/user.php(221): do_action_ref_array('user_profile_up...', Array) #4 /var/www/html/wp-admin/user-edit.php(160): edit_user(170) #5 /var/www/html/wp-admin/profile.php(18): require_once('/var/www/html/w...') #6 /var/www/html/wp-admin/user/profile.php(13): require('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-content/plugins/acore-wp-plugin/src/hooks/user/user.php on line 39
```

**Comment by nicoaravena** [comment]
Should be close by #14?

**Comment by Helias** [comment]
not sure, I don't think so
